define('creditcard_edit_form_securitycode.tpl', ['Handlebars','Handlebars.CompilerNameLookup'], function (Handlebars, compilerNameLookup){ var template = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var helper, helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression, functionType="function";
  return " <div class=\"creditcard-edit-form-securitycode\"><div class=\"creditcard-edit-form-securitycode-group\" data-input=\"ccsecuritycode\" data-validation=\"control-group\"><label class=\"creditcard-edit-form-securitycode-group-label\" for=\"ccsecuritycode\"> "
    + escapeExpression(((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || helperMissing).call(depth0, "Security Number", {"name":"translate","hash":{},"data":data})))
    + " <span class=\"creditcard-edit-form-securitycode-group-label-required\">*</span></label><div class=\"creditcard-edit-form-securitycode-controls\" data-validation=\"control\"><input type=\"text\" class=\"creditcard-edit-form-securitycode-group-input\" id=\"ccsecuritycode\" name=\"ccsecuritycode\" value=\""
    + escapeExpression(((helper = (helper = compilerNameLookup(helpers,"value") || (depth0 != null ? compilerNameLookup(depth0,"value") : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"value","hash":{},"data":data}) : helper)))
    + "\" maxlength=\"4\"><a href=\"#\" class=\"creditcard-edit-form-securitycode-link\"><span class=\"creditcard-edit-form-securitycode-icon-container\"><i class=\"creditcard-edit-form-securitycode-icon\" data-toggle=\"popover\" data-placement=\"bottom\" data-title=\""
    + escapeExpression(((helper = (helper = compilerNameLookup(helpers,"creditCardHelpTitle") || (depth0 != null ? compilerNameLookup(depth0,"creditCardHelpTitle") : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"creditCardHelpTitle","hash":{},"data":data}) : helper)))
    + "\"/></span></a></div></div></div>  ";
},"useData":true}); template.Name = 'creditcard_edit_form_securitycode'; return template;});