define('login_register_reset_password.tpl', ['Handlebars','Handlebars.CompilerNameLookup'], function (Handlebars, compilerNameLookup){ var template = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression;
  return " <div class=\"login-register-reset-password-body\"><h2 class=\"login-register-reset-password-title\"> "
    + escapeExpression(((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || helperMissing).call(depth0, "Reset Password", {"name":"translate","hash":{},"data":data})))
    + " </h2><form class=\"login-register-reset-password-form\" novalidate><p class=\"login-register-reset-password-description\"> "
    + escapeExpression(((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || helperMissing).call(depth0, "Enter a new password below for <b>$(0)</b>", (depth0 != null ? compilerNameLookup(depth0,"email") : depth0), {"name":"translate","hash":{},"data":data})))
    + " </p><fieldset><div class=\"login-register-reset-password-control-group\" data-validation=\"control-group\"><label class=\"login-register-reset-password-control-label\" for=\"password\"> "
    + escapeExpression(((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || helperMissing).call(depth0, "Password <small class=\"login-register-reset-password-forgot-password-form-required\">*</small>", {"name":"translate","hash":{},"data":data})))
    + " </label><div class=\"login-register-reset-password-controls\" data-validation=\"control\"><input type=\"password\" class=\"login-register-reset-password-input\" id=\"password\" name=\"password\" value=\"\"></div></div><div class=\"login-register-reset-password-control-group\" data-validation=\"control-group\"><label class=\"login-register-reset-password-control-label\" for=\"confirm_password\">"
    + escapeExpression(((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || helperMissing).call(depth0, "Confirm Password <small class=\"login-register-reset-password-forgot-password-form-required\">*</small>", {"name":"translate","hash":{},"data":data})))
    + "</label><div class=\"login-register-reset-password-controls\" data-validation=\"control\"><input type=\"password\" class=\"login-register-reset-password-input\" id=\"confirm_password\" name=\"confirm_password\" value=\"\"></div></div><div data-type=\"alert-placeholder\"></div><div class=\"login-register-reset-password-control-group\"><button type=\"submit\" class=\"login-register-reset-password-submit\">"
    + escapeExpression(((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || helperMissing).call(depth0, "Change Password", {"name":"translate","hash":{},"data":data})))
    + "</button><a class=\"login-register-reset-password-sign-in\" href=\"/login-register\" data-target=\".register\">"
    + escapeExpression(((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || helperMissing).call(depth0, "Cancel & Return To Log in", {"name":"translate","hash":{},"data":data})))
    + "</a></div></fieldset></form></div>  ";
},"useData":true}); template.Name = 'login_register_reset_password'; return template;});