define('product_details_full.tpl', ['Handlebars','Handlebars.CompilerNameLookup'], function (Handlebars, compilerNameLookup){ var template = Handlebars.template({"1":function(depth0,helpers,partials,data) {
  var stack1, buffer = " <form id=\"product-details-full-form\" data-action=\"submit-form\" method=\"POST\"><section class=\"product-details-full-info\"><div id=\"banner-summary-bottom\" class=\"product-details-full-banner-summary-bottom\"></div></section><section data-view=\"Product.Options\"></section><div data-view=\"Product.Sku\"></div><div data-view=\"Product.Price\"></div><div data-view=\"Quantity.Pricing\"></div><div data-view=\"Product.Stock.Info\"></div> ";
  stack1 = compilerNameLookup(helpers,"if").call(depth0, (depth0 != null ? compilerNameLookup(depth0,"isPriceEnabled") : depth0), {"name":"if","hash":{},"fn":this.program(2, data),"inverse":this.noop,"data":data});
  if (stack1 != null) { buffer += stack1; }
  return buffer + " <div data-view=\"StockDescription\"></div><div data-view=\"SocialSharing.Flyout\" class=\"product-details-full-social-sharing\"></div><div class=\"product-details-full-main-bottom-banner\"><div id=\"banner-summary-bottom\" class=\"product-details-full-banner-summary-bottom\"></div></div></form> ";
},"2":function(depth0,helpers,partials,data) {
  return " <div data-view=\"Quantity\"></div><section class=\"product-details-full-actions\"><div class=\"product-details-full-actions-container\"><div data-view=\"MainActionView\"></div></div><div class=\"product-details-full-actions-container\"><div data-view=\"AddToProductList\" class=\"product-details-full-actions-addtowishlist\"></div><div data-view=\"ProductDetails.AddToQuote\" class=\"product-details-full-actions-addtoquote\"></div></div></section> ";
  },"4":function(depth0,helpers,partials,data) {
  return " <div data-view=\"GlobalViewsMessageView.WronglyConfigureItem\"></div> ";
  },"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var stack1, helper, functionType="function", helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression, buffer = " <div class=\"product-details-full\"><div data-cms-area=\"item_details_banner\" data-cms-area-filters=\"page_type\"></div><header class=\"product-details-full-header\"><div id=\"banner-content-top\" class=\"product-details-full-banner-top\"></div></header><div class=\"product-details-full-divider-desktop\"></div><article class=\"product-details-full-content\" itemscope itemtype=\"https://schema.org/Product\"><meta itemprop=\"url\" content=\""
    + escapeExpression(((helper = (helper = compilerNameLookup(helpers,"itemUrl") || (depth0 != null ? compilerNameLookup(depth0,"itemUrl") : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"itemUrl","hash":{},"data":data}) : helper)))
    + "\"><div id=\"banner-details-top\" class=\"product-details-full-banner-top-details\"></div><section class=\"product-details-full-main-content\"><div class=\"product-details-full-content-header\"><h1 class=\"product-details-full-content-header-title\" itemprop=\"name\">"
    + escapeExpression(((helper = (helper = compilerNameLookup(helpers,"pageHeader") || (depth0 != null ? compilerNameLookup(depth0,"pageHeader") : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"pageHeader","hash":{},"data":data}) : helper)))
    + "</h1><div class=\"product-details-full-rating\" data-view=\"Global.StarRating\"></div><div data-cms-area=\"item_info\" data-cms-area-filters=\"path\"></div></div><div class=\"product-details-full-main-content-left\"><div class=\"product-details-full-image-gallery-container\"><div id=\"banner-image-top\" class=\"content-banner banner-image-top\"></div><div data-view=\"Product.ImageGallery\"></div><div id=\"banner-image-bottom\" class=\"content-banner banner-image-bottom\"></div></div></div><div class=\"product-details-full-main-content-right\"><div class=\"product-details-full-divider\"></div><div class=\"product-details-full-main\"> ";
  stack1 = compilerNameLookup(helpers,"if").call(depth0, (depth0 != null ? compilerNameLookup(depth0,"isItemProperlyConfigured") : depth0), {"name":"if","hash":{},"fn":this.program(1, data),"inverse":this.program(4, data),"data":data});
  if (stack1 != null) { buffer += stack1; }
  return buffer + " <div id=\"banner-details-bottom\" class=\"product-details-full-banner-details-bottom\" data-cms-area=\"item_info_bottom\" data-cms-area-filters=\"page_type\"></div></div></div></section><section data-view=\"Product.Information\"></section><div class=\"product-details-full-divider-desktop\"></div><div data-view=\"ProductReviews.Center\"></div><div class=\"product-details-full-content-related-items\"><div data-view=\"Related.Items\"></div></div><div class=\"product-details-full-content-correlated-items\"><div data-view=\"Correlated.Items\"></div></div><div id=\"banner-details-bottom\" class=\"content-banner banner-details-bottom\" data-cms-area=\"item_details_banner_bottom\" data-cms-area-filters=\"page_type\"></div></article></div>  ";
},"useData":true}); template.Name = 'product_details_full'; return template;});