define('quick_add.tpl', ['Handlebars','Handlebars.CompilerNameLookup'], function (Handlebars, compilerNameLookup){ var template = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var helper, functionType="function", helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression;
  return " <div class=\"quick-add-box\"><form novalidate action=\"#\"><div class=\"quick-add-box-left\" data-input=\"quickaddSearch\" data-validation=\"control-group\"><label for=\"quickaddSearch\">"
    + escapeExpression(((helper = (helper = compilerNameLookup(helpers,"itemTitle") || (depth0 != null ? compilerNameLookup(depth0,"itemTitle") : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"itemTitle","hash":{},"data":data}) : helper)))
    + "</label><div class=\"quick-add-box-input\" data-validation=\"control\"><div class=\"quick-add-box-input-search\" data-view=\"ItemsSearcher\"></div><a class=\"quick-add-box-input-search-reset\" data-type=\"quick-add-reset\"><i class=\"quick-add-box-input-search-reset-icon\"></i></a></div></div><div class=\"quick-add-box-right\" data-input=\"quickaddSearch\" data-validation=\"control-group\"><label for=\"quantity\">"
    + escapeExpression(((helper = (helper = compilerNameLookup(helpers,"quantityTitle") || (depth0 != null ? compilerNameLookup(depth0,"quantityTitle") : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"quantityTitle","hash":{},"data":data}) : helper)))
    + "</label><div class=\"quick-add-box-right-main\"><div class=\"quick-add-box-right-input\" data-validation=\"control\"><div class=\"quick-add-box-right-actionable-input-qty\"><button type=\"button\" class=\"quick-add-box-right-quantity-remove\" data-action=\"minus\">-</button><input data-type=\"quantity-input\" type=\"number\" name=\"quantity\" id=\"quantity\" class=\"quick-add-box-right-quantity-value\" min=\"1\"><button type=\"button\" class=\"quick-add-box-right-quantity-add\" data-action=\"plus\">+</button></div><small class=\"quick-add-box-minimum-top\" data-type=\"minimum-quantity\"></small></div><button class=\"quick-add-box-button\" type=\"submit\">"
    + escapeExpression(((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || helperMissing).call(depth0, "Add Item", {"name":"translate","hash":{},"data":data})))
    + "</button><small class=\"quick-add-box-minimum-bottom\" data-type=\"minimum-quantity\"></small></div></div></form></div>  ";
},"useData":true}); template.Name = 'quick_add'; return template;});