define('store_locator_main.tpl', ['Handlebars','Handlebars.CompilerNameLookup'], function (Handlebars, compilerNameLookup){ var template = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var helper, functionType="function", helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression;
  return " <div class=\"store-locator-main\"><div class=\"store-locator-main-title\"><h1>"
    + escapeExpression(((helper = (helper = compilerNameLookup(helpers,"title") || (depth0 != null ? compilerNameLookup(depth0,"title") : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"title","hash":{},"data":data}) : helper)))
    + "</h1></div><div class=\"store-locator-main-layout\"><div class=\"store-locator-main-layout-left\"><div class=\"store-locator-main-search\" data-view=\"StoreLocatorSearch\"></div><div class=\"store-locator-main-results\" data-view=\"StoreLocatorResults\"></div><div class=\"store-locator-main-see-all-stores\"><a data-touchpoint=\""
    + escapeExpression(((helper = (helper = compilerNameLookup(helpers,"touchpoint") || (depth0 != null ? compilerNameLookup(depth0,"touchpoint") : depth0)) != null ? helper : helperMissing),(typeof helper === functionType ? helper.call(depth0, {"name":"touchpoint","hash":{},"data":data}) : helper)))
    + "\" data-hashtag=\"stores/all\" href=\"stores/all\">"
    + escapeExpression(((compilerNameLookup(helpers,"translate") || (depth0 && compilerNameLookup(depth0,"translate")) || helperMissing).call(depth0, "See complete list of stores", {"name":"translate","hash":{},"data":data})))
    + "</a></div></div><div class=\"store-locator-main-layout-right\"><div class=\"store-locator-main-map\" data-view=\"StoreLocatorMap\" data-type=\"map-view\"></div></div></div></div>  ";
},"useData":true}); template.Name = 'store_locator_main'; return template;});